# See https://github.com/binder-examples/conda
name: radis-env
channels:
- conda-forge
- astropy
dependencies:
- python=3.8
- numpy
- scipy>=1.4.0
- matplotlib
- cython
- pandas>=1.0.5
- pytables  # for pandas to HDF5 export
- plotly    # used in line-survey
- astropy  # Unit aware calculations
- plotly>=2.5.1  # for line survey HTML output
- termcolor  # terminal colors
- configparser
- astroquery>=0.3.9  # to fetch HITRAN databases
- pytest  # to run test suite
- joblib  # for parallel loading of SpecDatabase
- numba  # just-in-time compiler
- h5py   # load HDF5
- pip
- pip:
  - publib>=0.3.2  # Plotting styles for Matplotlib
  - hitran-api     # HAPI, used to access TIPS partition functions
  - json-tricks>=3.15.0  # to deal with non jsonable formats
  - mpldatacursor
  - tables  # for pandas to HDF5 export
  - vaex    # load HDF5 files
